server {
    listen 80;
    root /usr/share/nginx/html;

    location = /exacto {
        return 200 "coincidencia exacta";
    }

    location /prefijo/ {
        return 200 "prefijo con prioridad";
    }

    location ~ \.txt$ {
        return 200 "regex con .txt";
    }

    location / {
        return 200 "generico";
    }
}