# Correr 3 backends: docker run --name backend-1 -p 8081:80 ... (igual con -2 y -3)
# y conectarlos a la misma red docker que lab.
upstream backends {
    server backend-1:80;
    server backend-2:80;
    server backend-3:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://backends;
    }
}