log_format detallado '$remote_addr [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_user_agent"';

server {
    listen 80;
    root /usr/share/nginx/html;
    access_log /var/log/nginx/detallado.log detallado;
}