server {
    listen 80;
    root /usr/share/nginx/html;

    error_page 404 /errores/404.html;
    location = /errores/404.html {
        internal;
    }

    error_page 502 /errores/502.html;
    location = /errores/502.html {
        internal;
    }
}